train_file: 'captioning_train.csv'
val_file: 'captioning_val.csv'
test_file: 'captioning_test.csv'

read_local_data: true

video_root: "parent_directory_of_videos/"

text_decoder: 'nlp_gpt3_text-generation_1.3B/'
text_cfg: configs/models/config_gpt3_1.3B.json
visual_cfg: 'configs/models/clip-b16.json'

megatron_cfg: {
  "world_size": 1,
  "model_parallel_size": 8,
  "tensor_model_parallel_size": 8,
}

batch_size: 24
num_workers: 24

max_length: 80

freeze_vit: false
freeze_text_decoder: true

num_learnable_token: 128
use_cls: true

num_frames: 16
prompt: ""

optimizer: {
  lr: 2e-5,
  opt: "AdamW",
  weight_decay: 0.05,
  clip_grad: 3.0,
  opt_betas: [0.9, 0.999],
  opt_eps: 1e-6
}

schedular: {
  epochs: 10,
  min_lr: 1e-6,
  warmup_epochs: -1,
  warmup_steps: 100,
  lr_sched_type: "cosine"
}