train_file: 'youku_ret_train.jsonl'
val_file: 'youku_ret_val.jsonl'
test_file: 'youku_ret_test.jsonl'

read_local_data: true

video_root: "path/to/videos/retrieval/"

text_decoder: 'nlp_gpt3_text-generation_2.7B/'
text_cfg: configs/models/config_gpt3_2.7B.json
visual_cfg: 'configs/models/clip-b16.json'

use_cls: true

megatron_cfg: {
  "world_size": 1,
  "model_parallel_size": 1,
  "tensor_model_parallel_size": 1,
}

batch_size: 64
num_workers: 24
max_length: 80

freeze_vit: false
freeze_text_decoder: true

num_learnable_token: 128

temp: 0.07
embed_dim: 256

optimizer: {
  lr: 1e-4,
  opt: "AdamW",
  weight_decay: 0.05,
  clip_grad: 3.0,
  opt_betas: [0.9, 0.999],
  opt_eps: 1e-8
}

schedular: {
  epochs: 50,
  min_lr: 1e-7,
  warmup_epochs: 2,
  warmup_steps: -1,
  lr_sched_type: "cosine"
}

